// Generated by node build-web-core.mjs from the unchanged CLI functions.
// Do not edit this file directly. No Node imports or network operations.

export function parseCsv(text) {
  text = text.replace(/^\uFEFF/, '');
  const rows = [];
  let row = [], value = '', quoted = false, closed = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c === '"' && text[i + 1] === '"') { value += '"'; i++; }
      else if (c === '"') { quoted = false; closed = true; }
      else value += c;
    } else if (c === ',' || c === '\n' || c === '\r') {
      row.push(value); value = ''; closed = false;
      if (c !== ',') {
        rows.push(row); row = [];
        if (c === '\r' && text[i + 1] === '\n') i++;
      }
    } else if (c === '"' && value === '' && !closed) quoted = true;
    else {
      if (closed || c === '"') throw new Error('Invalid CSV quoting');
      value += c;
    }
  }
  if (quoted) throw new Error('Unterminated quoted CSV field');
  if (row.length || value !== '' || closed) rows.push([...row, value]);
  return rows;
}

export function compareCsv(beforeText, afterText, keys) {
  if (!keys?.length || new Set(keys).size !== keys.length) throw new Error('Specify unique key column names');
  function index(text, label) {
    const [header, ...rows] = parseCsv(text);
    if (!header?.length || header.some(h => !h.trim()) || new Set(header).size !== header.length)
      throw new Error(`${label}: invalid header`);
    const positions = keys.map(k => header.indexOf(k));
    if (positions.includes(-1)) throw new Error(`${label}: key column not found`);
    const map = new Map();
    for (const [i, row] of rows.entries()) {
      if (row.length !== header.length) throw new Error(`${label}: record ${i+2} has wrong column count`);
      const values = positions.map(p => row[p]);
      if (values.some(v => !v.trim())) throw new Error(`${label}: record ${i+2} has empty key`);
      const key = JSON.stringify(values);
      if (map.has(key)) throw new Error(`${label}: record ${i+2} has duplicate key`);
      map.set(key, Object.fromEntries(header.map((h,j) => [h,row[j]])));
    }
    return {header,map};
  }
  const before = index(beforeText,'before'), after = index(afterText,'after');
  if (before.header.length !== after.header.length || before.header.some(h => !after.header.includes(h)))
    throw new Error('Column names differ between snapshots');
  const added = [], removed = [], changed = [];
  let unchanged = 0;
  for (const [id, oldRow] of before.map) {
    if (!after.map.has(id)) { removed.push(oldRow); continue; }
    const newRow = after.map.get(id);
    const fields = before.header.filter(h => oldRow[h] !== newRow[h]);
    if (fields.length) changed.push({key:Object.fromEntries(keys.map(k=>[k,oldRow[k]])),
      fields:fields.map(column=>({column,before:oldRow[column],after:newRow[column]}))});
    else unchanged++;
  }
  for (const [id,row] of after.map) if (!before.map.has(id)) added.push(row);
  return {keys,summary:{before:before.map.size,after:after.map.size,added:added.length,
    removed:removed.length,changed:changed.length,unchanged},added,removed,changed};
}

const escapeHtml = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cell = value => '<td>'+escapeHtml(value)+'</td>';
function table(headers, rows) {
  if (!rows.length) return '<p>无记录。</p>';
  return '<div class="table-wrap"><table><thead><tr>'+headers.map(h=>'<th scope="col">'+escapeHtml(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(cell).join('')+'</tr>').join('')+'</tbody></table></div>';
}
export function compareReport(beforeText, afterText, keys) {
  const result = compareCsv(beforeText, afterText, keys);
  const summaryNames = {before:'上期记录',after:'本期记录',added:'新增',removed:'删除',changed:'修改记录',unchanged:'未变'};
  const recordSection = (title, rows) => {
    const columns = rows.length ? Object.keys(rows[0]) : [];
    return '<section><h2>'+title+'（'+rows.length+'）</h2>'+table(columns,rows.map(r=>columns.map(c=>r[c])))+'</section>';
  };
  const modified = result.changed.flatMap(r=>r.fields.map(f=>[...keys.map(k=>r.key[k]),f.column,f.before,f.after]));
  const html = '<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CSV 快照变更报告</title>'+
'<style>body{font:16px/1.65 system-ui,sans-serif;color:#172b42;background:#f4f7fa;margin:0}main{max-width:1100px;margin:32px auto;padding:32px;background:white}h1{margin-top:0}h2{margin-top:32px}.summary{display:flex;flex-wrap:wrap;gap:12px}.stat{background:#edf4fa;padding:12px 20px;border-radius:8px}.stat strong{display:block;font-size:28px}table{border-collapse:collapse;width:100%;margin:12px 0}td,th{border:1px solid #ccd5df;padding:8px 12px;text-align:left;white-space:pre-wrap;overflow-wrap:anywhere}th{background:#edf4fa}.table-wrap{overflow:auto}.note{color:#526479}@media print{body{background:white}main{margin:0;padding:0}.table-wrap{overflow:visible}thead{display:table-header-group}tr{break-inside:avoid}}</style>'+
'<main><h1>CSV 快照变更报告</h1><p class="note">按 '+keys.map(escapeHtml).join(' + ')+' 精确配对。相同记录的列顺序变化不计为修改。</p><div class="summary">'+Object.entries(result.summary).map(([k,v])=>'<div class="stat">'+summaryNames[k]+'<strong>'+v+'</strong></div>').join('')+'</div>'+
'<section><h2>修改明细（'+result.summary.changed+' 条记录，'+modified.length+' 个字段）</h2>'+table([...keys,'变更字段','修改前','修改后'],modified)+'</section>'+
recordSection('新增记录',result.added)+recordSection('删除记录',result.removed)+
'<p class="note">未变记录不逐条展示。本报告包含原始字段值，分享前请脱敏。空白单元格表示空字符串；数值按原文本比较，不计算金额或判断业务正确性。使用浏览器打印功能可保存为 PDF。</p></main></html>';
  return {html,summary:result.summary};
}
